
HYPERSWITCH = 'hyperswitch'
HYPERSWITCH_UPDATE = 'hyperswitch-update'
HYPERSWITCH_CALLBACK = 'hyperswitch-callback'

PROVIDERPORT = 'providerport'


PAGINATION_INFINITE = 'infinite'

SORT_DIRECTION_ASC = 'asc'
SORT_DIRECTION_DESC = 'desc'

COMMON_PREFIXES = {
    HYPERSWITCH: '',
}

DESCRIPTION_FIELD_SIZE = 255
TENANT_ID_FIELD_SIZE = 255
UUID_FIELD_SIZE = 36
STATUS_FIELD_SIZE = 16